  variables:
    MsBuildPath : "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe"
    MsBuildPath64 : "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\amd64\\MSBuild.exe"
    NugetPath : "C:\\gitlab-runner\\nuget"
    SolutionName : "Invoice OTC.sln"
  
  stages: # tipe dari job
    - restore # stage untuk merestore paket nuget
    - build # stage untuk proses build  
    
  cache:
    untracked: true
    paths:    
      - lib # folder hasil restore nuget package    
  
  restore_nuget_package: # job 1
    stage: restore
    script:
      - echo "Sedang merestore paket nuget untuk ${SolutionName}..."
      - "${NugetPath} restore ${SolutionName}"  
      
  build_solution: # job 2
    stage: build
    script:     
      - echo "Sedang melakukan proses build 32 bit untuk ${SolutionName}..."
      - "${MsBuildPath} ${SolutionName}"    
      - echo "Sedang melakukan proses build 64 bit untuk $SolutionName..."
      - "${MsBuildPath64} ${SolutionName}"    
    only:
      - master # validasi untuk branch atau tag