  stages: # tipe dari job
    - restore # stage untuk merestore paket nuget
    - build # stage untuk proses build  
    
  cache:
    untracked: true
    paths:    
      - lib # folder hasil restore nuget package    
  
  restore_nuget_package: # job 1
    stage: restore
    script: 
        - .\restore.ps1 | Out-File c:\gitlab-runner\helloworld.txt
        
  build_solution: # job 2
    stage: build 
    script:     
      - .\build.ps1 | Out-File c:\gitlab-runner\helloworld.txt 
    only:
      - master # validasi untuk branch atau tag