  variables:
    MsBuildPath: "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe"
    NugetPath: "C:\\gitlab-runner\\nuget"
    SolutionName: "Invoice OTC.sln"
  
  stages: # tipe dari job
    - restore # stage untuk merestore paket nuget
    - build # stage untuk proses build  
    
  cache:
    untracked: true
    paths:    
      - lib # folder hasil restore nuget package    
  
  restore_nuget_package: # job 1
    stage: restore
    script:
      - echo "Sedang merestore paket nuget untuk %SolutionName%..."
      - '"%NugetPath%" restore "%SolutionName%"'  
      
  build_solution: # job 2
    stage: build
    script:     
      - echo "Sedang melakukan proses build untuk %SolutionName%..."
      - '"%MsBuildPath%" "%SolutionName%"'    
    only:
      - master # validasi untuk branch atau tag