#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice_OTC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OTF_Invoice")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertITEM(ITEM instance);
    partial void UpdateITEM(ITEM instance);
    partial void DeleteITEM(ITEM instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Invoice_OTC.Properties.Settings.Default.OTF_InvoiceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ITEM> ITEMs
		{
			get
			{
				return this.GetTable<ITEM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ITEM")]
	public partial class ITEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ITEMCODE;
		
		private string _ITEMNAME;
		
		private string _ITEMSORT;
		
		private string _Brand;
		
		private string _Jenis;
		
		private string _Category;
		
		private string _SubCategory;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<bool> _Stat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnITEMNAMEChanging(string value);
    partial void OnITEMNAMEChanged();
    partial void OnITEMSORTChanging(string value);
    partial void OnITEMSORTChanged();
    partial void OnBrandChanging(string value);
    partial void OnBrandChanged();
    partial void OnJenisChanging(string value);
    partial void OnJenisChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnSubCategoryChanging(string value);
    partial void OnSubCategoryChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnStatChanging(System.Nullable<bool> value);
    partial void OnStatChanged();
    #endregion
		
		public ITEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNAME", DbType="VarChar(50)")]
		public string ITEMNAME
		{
			get
			{
				return this._ITEMNAME;
			}
			set
			{
				if ((this._ITEMNAME != value))
				{
					this.OnITEMNAMEChanging(value);
					this.SendPropertyChanging();
					this._ITEMNAME = value;
					this.SendPropertyChanged("ITEMNAME");
					this.OnITEMNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMSORT", DbType="Char(5)")]
		public string ITEMSORT
		{
			get
			{
				return this._ITEMSORT;
			}
			set
			{
				if ((this._ITEMSORT != value))
				{
					this.OnITEMSORTChanging(value);
					this.SendPropertyChanging();
					this._ITEMSORT = value;
					this.SendPropertyChanged("ITEMSORT");
					this.OnITEMSORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="VarChar(20)")]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this.OnBrandChanging(value);
					this.SendPropertyChanging();
					this._Brand = value;
					this.SendPropertyChanged("Brand");
					this.OnBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jenis", DbType="VarChar(30)")]
		public string Jenis
		{
			get
			{
				return this._Jenis;
			}
			set
			{
				if ((this._Jenis != value))
				{
					this.OnJenisChanging(value);
					this.SendPropertyChanging();
					this._Jenis = value;
					this.SendPropertyChanged("Jenis");
					this.OnJenisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(25)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategory", DbType="VarChar(50)")]
		public string SubCategory
		{
			get
			{
				return this._SubCategory;
			}
			set
			{
				if ((this._SubCategory != value))
				{
					this.OnSubCategoryChanging(value);
					this.SendPropertyChanging();
					this._SubCategory = value;
					this.SendPropertyChanged("SubCategory");
					this.OnSubCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stat", DbType="Bit")]
		public System.Nullable<bool> Stat
		{
			get
			{
				return this._Stat;
			}
			set
			{
				if ((this._Stat != value))
				{
					this.OnStatChanging(value);
					this.SendPropertyChanging();
					this._Stat = value;
					this.SendPropertyChanged("Stat");
					this.OnStatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
