<?xml version="1.0" encoding="utf-8"?><Database Name="OTF_Invoice" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\sqlexpress;Initial Catalog=OTF_Invoice;Integrated Security=True" SettingsObjectName="Invoice_OTC.Properties.Settings" SettingsPropertyName="OTF_InvoiceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ITEM" Member="ITEMs">
    <Type Name="ITEM">
      <Column Name="ITEMCODE" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ITEMNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ITEMSORT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Jenis" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SubCategory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Stat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>